### ISSUE TITLE
Peers are getting rejected with reason: Duplicate

### ISSUE THREAD

**Issue by 24thsaint** [mafintosh/discovery-swarm#47]
Hello! I did a simple p2p chat system.

I was wondering why I'm getting duplicate, banned, and redundant connections when connecting to a peer... Sometimes the peers connect properly, and sometimes they don't because the peers are dropped due to the 'duplicate' reason.

While the documentation states that the duplicate connections are dropped and only one remains, why is it that the peers don't connect (well, sometimes they connect, sometimes they don't)? O_O

https://github.com/24thsaint/chattery-p2p

![screenshot from 2018-07-06 11-09-00](https://user-images.githubusercontent.com/8315544/42358066-6502168c-810d-11e8-82ef-c64870e8a025.png)

**Comment by pfrazee** [comment]
Those events don't all indicate a possible problem. Duplicate connections happen because multiple connections are tried; once detected, all but one duplicate is dropped. Duplicate candidate peers also occur and are rejected; again, no big deal. As for banning, usually a peer gets 'banned' because it fails to connect too many times.

**Comment by 24thsaint** [comment]
But why is it that when a peer is rejected, no connection is made?
Just like this one...

![screenshot from 2018-07-07 10-35-07](https://user-images.githubusercontent.com/8315544/42405991-9bd70fea-81d1-11e8-98b7-cd32b2c6ce81.png)

**Comment by pfrazee** [comment]
That *might* be an issue there. If you can create a test case and prove that a quick close/reconnect is getting rejected incorrectly, we'll fix that.

**Comment by 24thsaint** [comment]
Hello, I have here a sample test case...
One peer is an amazon EC2 virtual server and one is my own device.
https://github.com/24thsaint/chattery-p2p/blob/master/test-case-1/test.js

This is what it looks like instead of the messages sending back-and-forth between the peers:
![screenshot from 2018-07-09 15-42-41](https://user-images.githubusercontent.com/8315544/42437161-c0d7a3ae-838e-11e8-916a-b41584ae1dde.png)

**Comment by pfrazee** [comment]
@24thsaint both sides has a 'discovered' event for the other, followed by the 'rejected, reason: duplicate'. That means they are trying to connect to each other as expected, just failing to establish the connection.

**Comment by pfrazee** [comment]
These `'peer'` and `'peer-rejected'` events are 100% about the discovery process and not the connection process. It's emitting `'peer-rejected'` as a duplicate because it already had the given peer in its list of valid peers to connect to.

**Comment by 24thsaint** [comment]
Would there be a particular reason as to why the connections fail to be established?

Because when I keep on connecting-reconnecting, at some point a connection gets established... Gets me confused as to why the connections don't establish in a stable way remotely (as compared to how it works locally).

**Comment by 24thsaint** [comment]
Also kept me wondering... Why would the peer be there in the first place since this is a first-time connection on a new channel?

**Comment by pfrazee** [comment]
> Would there be a particular reason as to why the connections fail to be established?

Very hard to say without sitting down and doing a debug session. All I can say is that I think it's *unlikely* that the `peer-rejected` event is the cause, because there's nothing anomalous in what you've described and shown so far.

> Why would the peer be there and marked as duplicate whereas this is a first-time connection on a new channel?

In the log that you screenshotted, the peer is only rejected as a duplicate after one successful discovery. (The banned peer is another story.)

**Comment by 24thsaint** [comment]
Mhmm I see.
This answers my queries. Thank you for your time sir @pfrazee and thank you for this amazing project, more power! :1st_place_medal: :+1:
