### ISSUE TITLE
Is discovery broken?

### ISSUE THREAD

**Issue by staltz** [mafintosh/discovery-swarm#52]
I'm successfully using discovery-swarm and I'm thankful for it, but recently @noffle shared with me that @mafintosh said something along the lines that: "*discovery-swarm DHT discovery method has been broken for a long time: it defaults instead to doing signalling over a server Mafintosh runs*", the latter which I assume are the servers listed in `dat-swarm-defaults`. I have a hard time believing that discovery-channel over bittorrent-dht is *not at all working*, because I was debugging in WireShark the other day and it looked legitimate. I'm not sure I'm asking the right questions, so: is there anything seriously broken with this package?

**Comment by mafintosh** [comment]
Not that I know of. There is many thing we wanna improve with this layer in general (in fact we'll have an announcement coming out in the next days), but it does work.

This does BT DHT announcements/lookups and then does DNS discovery over multicast-dns and using 3 dns servers we run (I run one atm, two other community members run the other ones).

The UDP hole punching uses the 3 dns servers to work. Maybe that was, what I was referring to?

**Comment by staltz** [comment]
> The UDP hole punching uses the 3 dns servers to work. Maybe that was, what I was referring to?

Yes that makes sense. I'm interested in increasing the amount of dns servers, perhaps publishing a `ssb-swarm-defaults` too. Do you got a pointer to an easy to setup DNS server module?

I think this issue is answered, thanks maf

**Comment by RangerMauve** [comment]
The [dns-discovery](https://github.com/mafintosh/dns-discovery#cli) module has a CLI which lets you run a server.

```shell
dns-discovery listen --port=9090 --ttl=30
```
