### ISSUE TITLE
discovery-swarm works on mobile-data hotspots but not on mobile-data only

### ISSUE THREAD

**Issue by solydtech** [mafintosh/discovery-swarm#59]
This is a bit strange.
We ran the example in mobile device using nodejs-mobile. And it works fine if the mobile is on hot-spot of mobile, which is essentially mobile-service-provider's network.
But it doesn't work if hotspot is not enabled.

Do you find this behaviour aligned to philosophy of this lib?
How to overcome this?

**Comment by joehand** [comment]
That is surprising. How are use testing this? Discovery swarm requires some native modules which may not work on your phone but work on your computer.

I've had intermittent success with different mobile networks and haven't gotten a better sense of why.

**Comment by tim-coin** [comment]
I used nodejs-mobile. It works on mobile

**Comment by fejnartal** [comment]
Hello @solydtech

I'm using nodejs-mobile in Android and have been able to sync dats both in mobile-data and hostpot mode without problem.

I have noticed that nodejs-mobile+dat doesn't work well in battery-saving mode (I guess this is perfectly normal and Android related.)

You could also take a look at: https://github.com/staltz/dat-installer and see if your problem persist while using that App.

**Comment by okdistribute** [comment]
Works for us too, closing this
